# .github/workflows/flatpak_build.yml

name: Build Flatpak App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Flatpak and Flatpak Builder
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder

    - name: Install Flatpak Runtimes and SDKs
      run: |
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install --user --noninteractive flathub org.kde.Platform//6.7 org.kde.Sdk//6.7

    - name: Download Python Dependencies (Wheels) - NOVO PASSO
      run: |
        # Cria um diretório para os pacotes baixados
        mkdir -p ./python_wheels
        # Baixa os arquivos .whl para instalação offline.
        # Usa --user para baixar para o diretório local de pacotes do usuário
        # --no-deps para evitar baixar dependências de pacotes já disponíveis no runtime base
        # É importante verificar as versões exatas de PyQt5 e PyQtWebEngine necessárias.
        # Estas são versões comuns que podem funcionar com o runtime 6.7.
        pip3 download --no-deps "PyQt5==5.15.11" "PyQtWebEngine==5.15.7" -d ./python_wheels
      # Atenção: As versões 5.15.11 e 5.15.7 foram baseadas na sua instalação anterior.
      # Se der erro, pode ser necessário ajustar a versão do PyQt para ser compatível com o Python do runtime Flatpak.
      # O erro "Could not find a version that satisfies the requirement" pode ocorrer se a versão não existir para o Python 3.11.

    - name: Organize Flatpak Build Directory
      run: |
        mkdir -p flatpak-build/app-source
        mv navegador.py flatpak-build/app-source/
        mv org.pedrodev2025.NavegadorPyTech.desktop flatpak-build/app-source/
        mv org.pedrodev2025.NavegadorPyTech.png flatpak-build/app-source/

    - name: Build Flatpak Application
      run: |
        # Navega para o diretório de build
        cd flatpak-build
        # Executa o flatpak-builder
        flatpak-builder --repo=./repo-final --force-clean build-dir org.pedrodev2025.NavegadorPyTech.yaml

    - name: Upload Flatpak Repository as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Flatpak_NavegadorPyTech_Repo
        path: flatpak-build/repo-final/
        retention-days: 365
